/**
 * Copyright 2019 ForgeRock AS. All Rights Reserved
 *
 * Use of this code requires a commercial software license with ForgeRock AS.
 * or with one of its affiliates. All use shall be exclusively subject
 * to such license between the licensee and ForgeRock AS.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.forgerock.openbanking.tpp.shop.api;

import com.forgerock.openbanking.tpp.shop.model.PaymentEventsNotification;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Api(value = "shop", description = "the shop API")
@RequestMapping("/rest/shop/*")
public interface ShopApi {

    @RequestMapping(
            value = "/statusCallback",
            consumes = {"application/json; charset=utf-8"},
            method = RequestMethod.POST
    )
    ResponseEntity statusCallback(
            @ApiParam(value = "FRPaymentConsent submissions status", required = true)
            @Valid
            @RequestBody PaymentEventsNotification paymentEventsNotification
    );
}
