FROM node:10

WORKDIR /src
ADD ./projects/tpp/server/package.json ./projects/tpp/server/package-lock.json /src/

RUN npm ci

ADD ./projects/tpp/server /src

ENV PORT 80
RUN npm run build

EXPOSE 80

ENV DOMAIN ""
ENV TPP_URL "https://tpp.DOMAIN"
ENV BANK_URL "https://bank.DOMAIN"
ENV MONITORING_BACKEND_URL "https://monitoring.DOMAIN"
ENV RS_BACKEND_URL "https://rs.aspsp.DOMAIN"
ENV AUTHORIZATION_URL "https://as.aspsp.DOMAIN"
ENV DIRECTORY_BACKEND_URL "https://matls.service.directory.DOMAIN"
ENV JWKMS_BACKEND_URL "https://jwkms.DOMAIN"
ENV MATLS_BACKEND_URL "https://matls.as.aspsp.DOMAIN"
ENV NODE_ENV "production"

COPY projects/tpp/docker/start-server.sh /opt/start-server.sh
COPY projects/tpp/docker/deployment-settings.js /src/dist/deployment-settings.js
COPY projects/tpp/docker/ssl/bundled.perm /opt/bundled.perm

ENV NODE_EXTRA_CA_CERTS /opt/bundled.perm

CMD ["/opt/start-server.sh"]
