/**
 * Copyright 2019 ForgeRock AS. All Rights Reserved
 *
 * Use of this code requires a commercial software license with ForgeRock AS.
 * or with one of its affiliates. All use shall be exclusively subject
 * to such license between the licensee and ForgeRock AS.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.forgerock.openbanking.tpp.core.api.aspsp;

import com.forgerock.openbanking.tpp.config.AspspConfiguration;
import io.swagger.annotations.Api;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.text.ParseException;
import java.util.List;


@Api(value = "aspsp", description = "Register the current TPP to an ASPSP")
@RequestMapping("/open-banking/v1.1/aspsp/")
public interface AspspAPI {

    @RequestMapping(value = "/",
            produces = { "application/json; charset=utf-8" },
            method = RequestMethod.GET)
    ResponseEntity<List<AspspConfiguration>> getASPSPs(
    );

    @RequestMapping(value = "/",
            produces = { "application/json; charset=utf-8" },
            method = RequestMethod.POST)
    ResponseEntity<AspspConfiguration> registerToAllAspsps(
    ) throws ParseException;

    @RequestMapping(value = "/",
            method = RequestMethod.DELETE)
    ResponseEntity<AspspConfiguration> unregisterAll(
    );
}
