name: pull-request

on: [pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Check Copyright	
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-args: "license:check"

    - name: Build and Test	
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-args: "clean install"

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Auto merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
