name: pull-request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/pom.xml') }}
      - name: Docker login
        run: docker login eu.gcr.io --username fropenbanking --password ${{ secrets.CODEFRESH_DOCKER_REGISTRY_API_KEY }}

      - name: Check Copyright
        run: mvn license:check

      - name: Build and Test
        run: mvn clean verify

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
