name: pull-request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: 'zulu'
          cache: 'maven'
          architecture: x64

      - name: Docker login
        run: echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | base64 -d | docker login eu.gcr.io -u _json_key --password-stdin

      - name: Check Copyright
        run: mvn license:check

      - name: Build and Test
        run: mvn -B clean verify

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
