name: Build-UI Release

on:
  release:
    types: [ published ]
env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run tests
        working-directory: ./forgerock-openbanking-ui
        run: |
          npm ci
          npm run test.ci
          ./node_modules/@angular/cli/bin/ng lint
      - name: Prepare customers
        working-directory: ./forgerock-openbanking-ui
        run: git clone https://${{ secrets.FORGECLOUD_ACCESS_TOKEN }}@github.com/ForgeCloud/ob-customers.git customers
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: customers
          path: forgerock-openbanking-ui/customers
  build_tpp_backend:
    name: Build Tpp Backend App
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - working-directory: ./forgerock-openbanking-ui
        id: version
        run: |
          export VERSION=${RELEASE_VERSION}-${GITHUB_SHA::7}
          echo "::set-output name=BUILD_VERSION::$VERSION"
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: customers
          path: forgerock-openbanking-ui/customers
      - working-directory: ./forgerock-openbanking-ui
        run: cp -R ./customers/* themes/
      - name: Build TPP backend docker image
        working-directory: ./forgerock-openbanking-ui
        run: |
          export BUILD_VERSION=${{ steps.version.outputs.BUILD_VERSION }}
          echo "Building docker image eu.gcr.io/openbanking-214714/obri/tpp-node:${BUILD_VERSION}"
          echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | base64 -d | docker login eu.gcr.io -u _json_key --password-stdin
          docker build  --build-arg BUILD_VERSION=$BUILD_VERSION -f projects/tpp/docker/Dockerfile-server -t eu.gcr.io/openbanking-214714/obri/tpp-node:latest -t eu.gcr.io/openbanking-214714/obri/tpp-node:$BUILD_VERSION .
          docker push eu.gcr.io/openbanking-214714/obri/tpp-node:latest
          docker push eu.gcr.io/openbanking-214714/obri/tpp-node:$BUILD_VERSION
  build_tpp_ui:
    name: Build TPP App
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - working-directory: ./forgerock-openbanking-ui
        id: version
        run: |
          export VERSION=${RELEASE_VERSION}-${GITHUB_SHA::7}
          echo "::set-output name=BUILD_VERSION::$VERSION"
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: customers
          path: forgerock-openbanking-ui/customers
      - working-directory: ./forgerock-openbanking-ui
        run: cp -R ./customers/* themes/
      - name: Build TPP APP docker image
        working-directory: ./forgerock-openbanking-ui
        run: |
          export BUILD_VERSION=${{ steps.version.outputs.BUILD_VERSION }}
          echo "Building docker image eu.gcr.io/openbanking-214714/obri/tpp-ui:${BUILD_VERSION}"
          echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | base64 -d | docker login eu.gcr.io -u _json_key --password-stdin
          docker build --build-arg BUILD_VERSION=$BUILD_VERSION -f projects/tpp/docker/Dockerfile -t eu.gcr.io/openbanking-214714/obri/tpp-ui:latest -t eu.gcr.io/openbanking-214714/obri/tpp-ui:$BUILD_VERSION .
          docker push eu.gcr.io/openbanking-214714/obri/tpp-ui:latest
          docker push eu.gcr.io/openbanking-214714/obri/tpp-ui:$BUILD_VERSION
  update_ob_deploy:
    name: Update ob-deploy
    runs-on: ubuntu-latest
    needs: [build_tpp_ui, build_tpp_backend]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - working-directory: ./forgerock-openbanking-ui
        id: version
        run: |
          export VERSION=${RELEASE_VERSION}-${GITHUB_SHA::7}
          echo "::set-output name=BUILD_VERSION::$VERSION"
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: "forgeCloud/ob-deploy"
          token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          path: ob-deploy
      - name: Commit ob-deploy version update
        working-directory: ./ob-deploy
        run: |
          jq -M  '[ .[] | if ((.service == "tpp-ui" or .service == "tpp-node") and (.helmReference  | contains("obri-helm-charts/ui-template"))) then .version |= "${{ steps.version.outputs.BUILD_VERSION }}" else . end ]' releases-published.json > releases-published.json.tmp
          mv releases-published.json.tmp releases-published.json
          git config --global user.email "codefresh@codefresh.io"
          git config --global user.name "Codefresh"
          git add releases-published.json
          git commit --allow-empty -m "Bumping TPP UI & Backend version ${{ steps.version.outputs.BUILD_VERSION }}"
      - name: Temporarily disable "include administrators" protection
        id: disable_include_admins
        uses: benjefferies/branch-protection-bot@1.0.7
        if: always()
        with:
          access_token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          enforce_admins: false
          owner: forgeCloud
          repo: ob-deploy
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          directory: ./ob-deploy
          repository: "forgeCloud/ob-deploy"
          branch: master
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.7
        if: always()
        with:
          access_token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          enforce_admins: ${{ steps.disable_include_admins.outputs.initial_status }}
          owner: forgeCloud
          repo: ob-deploy
